### DATA CLEANING

 read in the csv files
 join - add the IMD decile to each row of the crime dataset

In [1]:
# hashed out as no longer needed
#  import the crime data files first which are in github releases folder 
#import requests

#url = "https://github.com/AnupmaDS1/Xmus-Jaxon-Flaxon-Waxon/releases/download/v1.1-data/WYP2024_2025.zip"
#r = requests.get(url)

#print(r.status_code)
#print(r.headers.get("content-type"))

#with open("Crimedata", "wb") as f:
#    f.write(r.content)

In [2]:
#check the filesize
#import os
#print(os.path.getsize("Crimedata.zip"))

In [3]:
# import libraries, read in the main csv files, name them as crime and imd and merge on LSOA code

import pandas as pd


crime = pd.read_csv('../data/raw/crime/WYP2025.csv')

In [4]:
# read in the IMD files

imd1 = pd.read_csv('../data/raw/deprivation/File_1_IoD2025_IOMD.csv')
imd5 = pd.read_csv('../data/raw/deprivation/File_5_IoD2025_ScoresFIOD.csv')
imd8 = pd.read_csv('../data/raw/deprivation/File_08_IoD2025_underlyingindicators_income.csv')
imd9 = pd.read_csv('../data/raw/deprivation/File_9_IoD2025_TransformedDomainScores.csv')

In [5]:
#check data

# Shape: (rows, columns)
print(crime.shape)

# Column names
print(crime.columns.tolist())


# Data types of each column
print(crime.dtypes)

(298385, 10)
['Crime ID', 'Month', 'Reported by', 'Longitude', 'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Crime type', 'Last outcome category']
Crime ID                     str
Month                        str
Reported by                  str
Longitude                float64
Latitude                 float64
Location                     str
LSOA code                    str
LSOA name                    str
Crime type                   str
Last outcome category        str
dtype: object

In [6]:
# First 10 rows
imd9.head(10)

,LSOA code (2021),LSOA name (2021),Local Authority District code (2024),Local Authority District name (2024),Income Score - exponentially transformed,Employment Score - exponentially transformed,Education Score - exponentially transformed,Health Score - exponentially transformed,Crime Score - exponentially transformed,Barriers Score - exponentially transformed,Living Environment Score - exponentially transformed
0,E01000001,City of London 001A,E09000001,City of London,0.017,0.032,0.001,0.440,0.039,3.273,89.930
1,E01000002,City of London 001B,E09000001,City of London,0.059,0.015,0.057,0.809,0.030,0.763,48.545
2,E01000003,City of London 001C,E09000001,City of London,6.652,5.075,2.471,11.040,4.791,2.376,44.308
3,E01000005,City of London 001E,E09000001,City of London,18.533,14.315,17.004,26.299,6.240,24.599,40.634
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,33.527,17.865,24.915,9.790,14.360,54.585,28.464
5,E01000007,Barking and Dagenham 015A,E09000002,Barking and Dagenham,53.791,32.779,15.572,27.011,53.356,54.384,21.185
6,E01000008,Barking and Dagenham 015B,E09000002,Barking and Dagenham,57.970,34.153,26.511,24.658,29.639,88.689,22.426
7,E01000009,Barking and Dagenham 016B,E09000002,Barking and Dagenham,41.304,30.436,37.146,22.648,52.902,55.694,52.039
8,E01000011,Barking and Dagenham 016C,E09000002,Barking and Dagenham,43.865,24.228,44.267,20.048,20.893,46.865,69.481
9,E01000012,Barking and Dagenham 015D,E09000002,Barking and Dagenham,55.281,31.424,27.335,13.317,24.917,83.808,26.045

In [7]:
# Quick structural summary: dtypes, non-null counts, memory usage
crime.info()

<class 'pandas.DataFrame'>
RangeIndex: 298385 entries, 0 to 298384
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               270516 non-null  str
 1   Month                  298385 non-null  str
 2   Reported by            298385 non-null  str
 3   Longitude              298385 non-null  float64
 4   Latitude               298385 non-null  float64
 5   Location               298385 non-null  str
 6   LSOA code              298385 non-null  str
 7   LSOA name              298385 non-null  str
 8   Crime type             298385 non-null  str
 9   Last outcome category  270516 non-null  str
dtypes: float64(2), str(8)
memory usage: 74.7 MB

In [8]:
# Basic descriptive stats for numeric columns
crime.describe()

           Longitude       Latitude
count  298385.000000  298385.000000
mean       -1.644382      53.758574
std         0.166992       0.070022
min        -2.177666      52.586004
25%        -1.775779      53.705111
50%        -1.638997      53.776991
75%        -1.528125      53.807229
max        -1.207936      54.821894

In [9]:
#amend col names to remove spaces for each of the dfs

crime.columns = crime.columns.str.strip().str.replace(' ', '_').str.lower()
imd1.columns = imd1.columns.str.strip().str.replace(' ', '_').str.lower()
imd5.columns = imd5.columns.str.strip().str.replace(' ', '_').str.lower()
imd8.columns = imd8.columns.str.strip().str.replace(' ', '_').str.lower()
imd9.columns = imd9.columns.str.strip().str.replace(' ', '_').str.lower()

In [10]:
# Column names remove spaces

print(crime.columns.tolist())
print(imd1.columns.tolist())
print(imd5.columns.tolist())
print(imd8.columns.tolist())
print(imd9.columns.tolist())

['crime_id', 'month', 'reported_by', 'longitude', 'latitude', 'location', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'index_of_multiple_deprivation_(imd)_rank_(where_1_is_most_deprived)', 'index_of_multiple_deprivation_(imd)_decile_(where_1_is_most_deprived_10%_of_lsoa']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'index_of_multiple_deprivation_(imd)_score', 'income_score_(rate)', 'employment_score_(rate)', 'education,_skills_and_training_score', 'health_deprivation_and_disability_score', 'crime_score', 'barriers_to_housing_and_services_score', 'living_environment_score', 'income_deprivation_affecting_children_index_(idaci)_score_(rate)', 'income_deprivation_affecting_older_people_(idaopi)_score_(rate)', 'children_and_young_people_sub-domain_score', 'adult_skills_sub-domain_score', 'geographical_barriers_sub-domain_score', 'wider_barriers_sub-domain_score', 'indoors_sub-domain_score', 'outdoors_sub-domain_score']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'income_domain_numerator', 'income_deprivation_affecting_children_index_(idaci)_numerator', 'income_deprivation_affecting_older_people_index_(idaopi)_numerator']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'income_score_-_exponentially_transformed', 'employment_score_-_exponentially_transformed', 'education_score_-_exponentially_transformed', 'health_score_-_exponentially_transformed', 'crime_score_-_exponentially_transformed', 'barriers_score_-_exponentially_transformed', 'living_environment_score_-_exponentially_transformed']

In [11]:
# sigh - remove the brackets in col names and replace with _ AND don't replace the last one
imd1.columns = (
    imd1.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

print(imd1.columns.tolist())

['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'index_of_multiple_deprivation_imd_rank_where_1_is_most_deprived', 'index_of_multiple_deprivation_imd_decile_where_1_is_most_deprived_10%_of_lsoa']

In [12]:
# repeat this on other imd dataframes

imd5.columns = (
    imd5.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

imd8.columns = (
    imd8.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

imd9.columns = (
    imd9.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

print(imd5.columns.tolist())
print(imd8.columns.tolist())
print(imd9.columns.tolist())

['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'index_of_multiple_deprivation_imd_score', 'income_score_rate', 'employment_score_rate', 'education,_skills_and_training_score', 'health_deprivation_and_disability_score', 'crime_score', 'barriers_to_housing_and_services_score', 'living_environment_score', 'income_deprivation_affecting_children_index_idaci_score_rate', 'income_deprivation_affecting_older_people_idaopi_score_rate', 'children_and_young_people_sub-domain_score', 'adult_skills_sub-domain_score', 'geographical_barriers_sub-domain_score', 'wider_barriers_sub-domain_score', 'indoors_sub-domain_score', 'outdoors_sub-domain_score']
['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'income_domain_numerator', 'income_deprivation_affecting_children_index_idaci_numerator', 'income_deprivation_affecting_older_people_index_idaopi_numerator']
['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'income_score_-_exponentially_transformed', 'employment_score_-_exponentially_transformed', 'education_score_-_exponentially_transformed', 'health_score_-_exponentially_transformed', 'crime_score_-_exponentially_transformed', 'barriers_score_-_exponentially_transformed', 'living_environment_score_-_exponentially_transformed']

In [13]:
crime.dtypes

crime_id                     str
month                        str
reported_by                  str
longitude                float64
latitude                 float64
location                     str
lsoa_code                    str
lsoa_name                    str
crime_type                   str
last_outcome_category        str
dtype: object

In [14]:
crime.head()

,crime_id,month,reported_by,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category
0,NaN,2025-01,West Yorkshire Police,-1.472961,53.599861,On or near Railway Walk,E01007439,Barnsley 001D,Anti-social behaviour,NaN
1,03b3bda6de7c51f6cd0820b7f998a1f878e7acbb6b18dd...,2025-01,West Yorkshire Police,-1.882755,53.924927,On or near Moorside Lane,E01010646,Bradford 001A,Burglary,Investigation complete; no suspect identified
2,6f9fe9a78c7ed106fadb658e4fd5313c1bb5bc5c8aa223...,2025-01,West Yorkshire Police,-1.878940,53.943744,On or near Cross End Fold,E01010646,Bradford 001A,Shoplifting,Investigation complete; no suspect identified
3,9cbc69a540485581b55d8d4723eb41b97d364bc98132d8...,2025-01,West Yorkshire Police,-1.872959,53.941733,On or near Cornerstones Close,E01010646,Bradford 001A,Vehicle crime,Investigation complete; no suspect identified
4,050a7cc33129f37f41cbbd38fe858e63e07dc239720be8...,2025-01,West Yorkshire Police,-1.883567,53.934131,On or near Cocking Lane,E01010646,Bradford 001A,Violence and sexual offences,Unable to prosecute suspect

In [15]:
#check how many blanks are in the outcome col 

print(crime['last_outcome_category'].isna().sum())
print((crime['last_outcome_category'].str.strip() == '').sum())

27869
0

In [17]:
#9.3% is a moderate amount — not negligible, do i need to invlude this in the write up and justify?
total_before = len(crime)
missing_outcome = crime['last_outcome_category'].isna().sum()
pct_missing = missing_outcome / total_before * 100
print(f"{pct_missing:.1f}% of rows have missing outcome")

9.3% of rows have missing outcome

In [18]:
crime.duplicated().sum()

np.int64(6198)

In [19]:
# Does your data have a unique ID column (e.g. crime reference number)?
crime.columns.tolist()

# If there's an ID column, check duplicates on the ID itself
crime['crime_id'].duplicated().sum()

# Look at a sample of the duplicate rows to inspect manually
crime[crime.duplicated(keep=False)].sort_values(by=crime.columns.tolist()).head(20)

,crime_id,month,reported_by,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category
7077,NaN,2025-01,West Yorkshire Police,-2.101759,53.711325,On or near Halling Place,E01010983,Calderdale 013B,Anti-social behaviour,NaN
7078,NaN,2025-01,West Yorkshire Police,-2.101759,53.711325,On or near Halling Place,E01010983,Calderdale 013B,Anti-social behaviour,NaN
7672,NaN,2025-01,West Yorkshire Police,-2.089073,53.716071,On or near Hallroyd Place,E01010884,Calderdale 022A,Anti-social behaviour,NaN
7673,NaN,2025-01,West Yorkshire Police,-2.089073,53.716071,On or near Hallroyd Place,E01010884,Calderdale 022A,Anti-social behaviour,NaN
6178,NaN,2025-01,West Yorkshire Police,-2.012956,53.741954,On or near Bridge Gate,E01010923,Calderdale 004F,Anti-social behaviour,NaN
6180,NaN,2025-01,West Yorkshire Police,-2.012956,53.741954,On or near Bridge Gate,E01010923,Calderdale 004F,Anti-social behaviour,NaN
6182,NaN,2025-01,West Yorkshire Police,-2.012956,53.741954,On or near Bridge Gate,E01010923,Calderdale 004F,Anti-social behaviour,NaN
6177,NaN,2025-01,West Yorkshire Police,-2.011470,53.741900,On or near A6033,E01010923,Calderdale 004F,Anti-social behaviour,NaN
6183,NaN,2025-01,West Yorkshire Police,-2.011470,53.741900,On or near A6033,E01010923,Calderdale 004F,Anti-social behaviour,NaN
1482,NaN,2025-01,West Yorkshire Police,-1.962110,53.820665,On or near Hanging Gate Lane,E01010857,Bradford 023D,Anti-social behaviour,NaN
1483,NaN,2025-01,West Yorkshire Police,-1.962110,53.820665,On or near Hanging Gate Lane,E01010857,Bradford 023D,Anti-social behaviour,NaN
6388,NaN,2025-01,West Yorkshire Police,-1.928274,53.753564,On or near Cold Edge Road,E01010920,Calderdale 007D,Anti-social behaviour,NaN
6390,NaN,2025-01,West Yorkshire Police,-1.928274,53.753564,On or near Cold Edge Road,E01010920,Calderdale 007D,Anti-social behaviour,NaN
681,NaN,2025-01,West Yorkshire Police,-1.927516,53.850696,On or near Bracken Bank Way,E01010715,Bradford 012A,Anti-social behaviour,NaN
682,NaN,2025-01,West Yorkshire Police,-1.927516,53.850696,On or near Bracken Bank Way,E01010715,Bradford 012A,Anti-social behaviour,NaN
714,NaN,2025-01,West Yorkshire Police,-1.927381,53.849411,On or near Central Drive,E01010718,Bradford 012C,Anti-social behaviour,NaN
715,NaN,2025-01,West Yorkshire Police,-1.927381,53.849411,On or near Central Drive,E01010718,Bradford 012C,Anti-social behaviour,NaN
716,NaN,2025-01,West Yorkshire Police,-1.927381,53.849411,On or near Central Drive,E01010718,Bradford 012C,Anti-social behaviour,NaN
298,NaN,2025-01,West Yorkshire Police,-1.909155,53.863887,On or near Beck Street,E01010710,Bradford 008G,Anti-social behaviour,NaN
299,NaN,2025-01,West Yorkshire Police,-1.909155,53.863887,On or near Beck Street,E01010710,Bradford 008G,Anti-social behaviour,NaN

In [20]:
# Check which crime types are driving this
crime[crime['crime_id'].isna()]['crime_type'].value_counts()

# Confirm: are duplicates almost entirely from ID-less categories?
no_id_dupes = crime[crime['crime_id'].isna() & crime.duplicated(keep=False)]
no_id_dupes['crime_type'].value_counts()

# Check if there are ANY duplicates among rows that DO have a crime_id
crime[crime['crime_id'].notna()].duplicated().sum()

np.int64(0)

In [21]:
# confirmed the duplication is fully explained by the missing-ID categories, and you can be confident the data itself isn't riddled with genuine export errors.

In [22]:
# Check if ASB rows have outcome data at all
crime[crime['crime_type'] == 'Anti-social behaviour']['last_outcome_category'].isna().mean()

np.float64(1.0)

In [23]:
# so the above confirms that 100% of Anti-social behaviour rows have a missing last_outcome_category

In [24]:
asb_total = (crime['crime_type'] == 'Anti-social behaviour').sum()
asb_total

np.int64(27869)

In [25]:
crime[(crime['crime_type'] != 'Anti-social behaviour') & (crime['last_outcome_category'].isna())]['crime_type'].value_counts()

Series([], Name: count, dtype: int64)

In [26]:
# when you filtered for rows where crime_type != 'Anti-social behaviour' and last_outcome_category is missing, there are zero matching rows, so value_counts() has nothing to count and returns an empty Series.
# In plain terms: no non-ASB crime type has any missing outcome at all. Every single missing outcome value in the entire 298,385-row dataset belongs to Anti-social behaviour, with no exceptions and no second pattern hiding anywhere else.

In [27]:
model_df = crime[crime['crime_type'] != 'Anti-social behaviour'].copy()
model_df['last_outcome_category'].isna().sum()  # should be 0

np.int64(0)

In [28]:
#what does last_outcome category contain (PRIOR TO ENCODING)
# 
model_df['last_outcome_category'].value_counts()

last_outcome_category
Unable to prosecute suspect                            109113
Investigation complete; no suspect identified          100941
Status update unavailable                               15054
Awaiting court outcome                                  11564
Court result unavailable                                10997
Local resolution                                         6465
Under investigation                                      5343
Further action is not in the public interest             3996
Action to be taken by another organisation               3667
Offender given a caution                                 1936
Further investigation is not in the public interest       917
Formal action is not in the public interest               499
Suspect charged as part of another case                    23
Offender given a drugs possession warning                   1
Name: count, dtype: int64

# encode the last outcome category into binary positive/negative outcome

In [29]:

# Snapshot before binary collapsing — preserves all outcome categories for potential multinomial modelling later
model_df_multiclass = model_df.copy()

In [ ]:
# unresolved rows removed — the rows with those four outcome categories are filtered out below




unresolved = [
    'Status update unavailable',
    'Awaiting court outcome',
    'Court result unavailable',
    'Under investigation'
]

model_df_binary = model_df[~model_df['last_outcome_category'].isin(unresolved)].copy()

# sanity check
model_df_binary.shape, model_df_binary['last_outcome_category'].isin(unresolved).sum()

((227558, 10), np.int64(0))

The next step below creates a new column outcome_binary (1 = positive outcome, 0 = negative outcome) while leaving last_outcome_category untouched as the original text

In [ ]:
# encode a binary version of the outcome category - using model_df_binary and outcome_binary is the new category

positive_outcomes = [
    'Offender given a caution',
    'Suspect charged as part of another case',
    'Offender given a drugs possession warning',
    'Local resolution'
]

model_df_binary['outcome_binary'] = model_df_binary['last_outcome_category'].apply(
    lambda x: 1 if x in positive_outcomes else 0
)

# sanity check
model_df_binary['outcome_binary'].value_counts()

outcome_binary
0    219133
1      8425
Name: count, dtype: int64

In [35]:
model_df_binary.head()

,crime_id,month,reported_by,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category,outcome_binary
1,03b3bda6de7c51f6cd0820b7f998a1f878e7acbb6b18dd...,2025-01,West Yorkshire Police,-1.882755,53.924927,On or near Moorside Lane,E01010646,Bradford 001A,Burglary,Investigation complete; no suspect identified,0
2,6f9fe9a78c7ed106fadb658e4fd5313c1bb5bc5c8aa223...,2025-01,West Yorkshire Police,-1.878940,53.943744,On or near Cross End Fold,E01010646,Bradford 001A,Shoplifting,Investigation complete; no suspect identified,0
3,9cbc69a540485581b55d8d4723eb41b97d364bc98132d8...,2025-01,West Yorkshire Police,-1.872959,53.941733,On or near Cornerstones Close,E01010646,Bradford 001A,Vehicle crime,Investigation complete; no suspect identified,0
4,050a7cc33129f37f41cbbd38fe858e63e07dc239720be8...,2025-01,West Yorkshire Police,-1.883567,53.934131,On or near Cocking Lane,E01010646,Bradford 001A,Violence and sexual offences,Unable to prosecute suspect,0
5,b43bb9c614a189dd550a9e877b409cdb6449d6ec1c1073...,2025-01,West Yorkshire Police,-1.880138,53.945417,On or near Aynholme Drive,E01010646,Bradford 001A,Violence and sexual offences,Investigation complete; no suspect identified,0

In [ ]:
#confirm the encoding logic actually mapped correctly. This should show category by category, which text label got mapped to 0 vs 1 

model_df_binary.groupby('last_outcome_category')['outcome_binary'].first()

last_outcome_category
Action to be taken by another organisation             0
Formal action is not in the public interest            0
Further action is not in the public interest           0
Further investigation is not in the public interest    0
Investigation complete; no suspect identified          0
Local resolution                                       1
Offender given a caution                               1
Offender given a drugs possession warning              1
Suspect charged as part of another case                1
Unable to prosecute suspect                            0
Name: outcome_binary, dtype: int64

In [ ]:
# merge or join the files on lsoa code


#merged = crime.merge(imd, left_on='LSOA code', right_on='LSOA code (2021)', how='left')